name: Build Archive Paper
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyAllPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload Test Results
        uses: actions/upload-artifact@v5
        with:
          name: Test Results
          path: |
            **/build/test-results/test/TEST-*.xml

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Rename Paperclip Jar
        run: mv archive-server/build/libs/archive-paperclip*.jar archive-server/build/libs/archive-paper-1.21.10.jar

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v5
        with:
          name: paperclip
          path: archive-server/build/libs/archive-paper-1.21.10.jar

