name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+1.21.1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Rename Paperclip Jar
        run: mv build/libs/archive-paper-paperclip*.jar build/libs/archive-paper-${{ github.ref_name }}.jar

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: paperclip
          path: build/libs/archive-paper-${{ github.ref_name }}.jar

      - name: Release Paperclip Artifact
        uses: ncipollo/release-action@v1
        with:
          name: The Archive Paper ${{ github.ref_name }}
          artifacts: build/libs/archive-paper-${{ github.ref_name }}.jar
          makeLatest: true
